/*
 * MetaSecret iOS API Header
 * This file is automatically generated. Do not modify manually.
 */
#include <stdint.h>
#include <stdbool.h>


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *generate_master_key(void);

char *init(const char *master_key_ptr);

char *get_state(void);

char *generate_user_creds(const char *vault_name_ptr);

char *sign_up(void);

char *update_membership(const char *candidate_ptr, const char *action_update_ptr);

char *clean_up_database(void);

char *split_secret(const char *secret_id_ptr, const char *secret_ptr);

char *find_claim_by(const char *secret_id_ptr);

char *recover(const char *secret_id_ptr);

char *accept_recover(const char *claim_id_ptr);

char *show_recovered(const char *secret_id_ptr);

void free_string(char *ptr);
