/*
 * MetaSecret iOS API Header
 * This file is automatically generated. Do not modify manually.
 */
#include <stdint.h>
#include <stdbool.h>


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *generate_master_key(void);

char *init(const char *master_key_ptr);

char *get_state(void);

void free_string(char *ptr);
