/* 
 * MetaSecret iOS API Header
 * This file is automatically generated. Do not modify manually.
 */
#include <stdint.h>
#include <stdbool.h>


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *sign_up(const char *user_name);

void free_string(char *ptr);
