/* 
 * MetaSecret iOS API Header
 * This file is automatically generated. Do not modify manually.
 */
#include <stdint.h>
#include <stdbool.h>


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Регистрация нового пользователя
 *
 * @param user_name Имя пользователя в UTF-8 строке
 * @return JSON строка с результатом операции; нужно освободить память с помощью free_string
 */
char *sign_up(const char *user_name);

/**
 * Освобождает память, выделенную для строки
 *
 * @param ptr Указатель на строку, возвращенную любой функцией API
 */
void free_string(char *ptr);
