[versions]
accompanistPager = "0.36.0"
agp = "8.9.1"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.10.1"
androidxMaterial = "1.7.8"
annotationJvm = "1.9.1"
compose-plugin = "1.7.3"
core = "1.15.0"
coroutinesVersion = "1.10.1"
foundationLayoutAndroid = "1.7.8"
jetbrainsKotlinxCoroutinesCoreVersion = "1.10.1"
koin = "4.0.1"
kotlin = "2.1.0"
lifecycleLivedataCoreKtx = "2.8.7"
multiplatformSettings = "1.3.0"
runtime = "1.7.8"
serialization = "1.7.3"
ui = "1.7.8"
uiAndroid = "1.7.8"
uiGraphicsAndroid = "1.7.8"
voyager = "1.1.0-beta03"
material = "1.12.0"
glance = "1.1.1"
uiAndroidVersion = "1.7.8"
activityKtx = "1.10.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPager" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }

#koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

#share settings
kotlinx-coroutines-core-v164 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrainsKotlinxCoroutinesCoreVersion" }
multiplatform-settings = {module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings"}
serialization-json = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
multiplatform-settings-serialization = {module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettings"}
coroutines-core = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion"}
settings-coroutine = {module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings"}

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
androidx-lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "lifecycleLivedataCoreKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroidVersion" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
